apiVersion: v1
kind: Service
metadata:
  name: kakao-payment-np
spec:
  type: NodePort
  selector:
    app: kakao-payment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30001

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kakao-payment
  name: kakao-payment-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kakao-payment
  strategy: {}
  template:
    metadata:
      labels:
        app: kakao-payment
    spec:
      containers:
        - image: ccf05017/kakao
          name: kakao-payment
          env:
          - name: PAYMENT_KEY
            valueFrom:
              secretKeyRef:
                name: payment-key
                key: payment-key
