spring:
  datasource:
    url: jdbc:h2:~/data/kakaopay
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

encryption:
  key: testKey
